### ISSUE TITLE
Program runs, but no file file created

### ISSUE THREAD

**Issue by mimijojo** [andrewkww/google-location-history-to-gpx#1]
When starting 

> ./extract '2022_JANUARY.json'

I get no error, but also no gpx file gets created.

How can I troubleshoot ?

**Comment by andrewkww** [comment]
Is your JSON file exported from Google Takeout?

**Comment by mimijojo** [comment]
Yes, I guess so.

This is the file structure I get :
```
/home/mimijojo/Downloads/split/Takeout
├── archive_browser.html
└── Location History
    ├── Records.json
    ├── Semantic Location History
    │   ├── 2020
    │   │   ├── 2020_APRIL.json
    │   │   ├── 2020_AUGUST.json
    │   │   ├── 2020_DECEMBER.json
    │   │   ├── 2020_FEBRUARY.json
    │   │   ├── 2020_JANUARY.json
    │   │   ├── 2020_JULY.json
    │   │   ├── 2020_JUNE.json
    │   │   ├── 2020_MARCH.json
    │   │   ├── 2020_MAY.json
    │   │   ├── 2020_NOVEMBER.json
    │   │   ├── 2020_OCTOBER.json
    │   │   └── 2020_SEPTEMBER.json
    │   ├── 2021
    │   │   ├── 2021_APRIL.json
    │   │   ├── 2021_AUGUST.json
    │   │   ├── 2021_DECEMBER.json
    │   │   ├── 2021_FEBRUARY.json
    │   │   ├── 2021_JANUARY.json
    │   │   ├── 2021_JULY.json
    │   │   ├── 2021_JUNE.json
    │   │   ├── 2021_MARCH.json
    │   │   ├── 2021_MAY.json
    │   │   ├── 2021_NOVEMBER.json
    │   │   ├── 2021_OCTOBER.json
    │   │   └── 2021_SEPTEMBER.json
    │   └── 2022
    │       ├── 2022_FEBRUARY.json
    │       └── 2022_JANUARY.json
    └── Settings.json

```
And these are the first lines of this 2022_JANUARY.json file :+1: 
```

{
  "timelineObjects": [{
    "activitySegment": {
      "startLocation": {
        "latitudeE7": 511411005,
        "longitudeE7": 43935510,
        "sourceInfo": {
          "deviceTag": 1837983635
        }
      },
      "endLocation": {
        "latitudeE7": 511443706,
        "longitudeE7": 44603933,
        "sourceInfo": {
          "deviceTag": 1837983635
        }
      },
      "duration": {
        "startTimestamp": "2022-01-08T15:50:46.639Z",
        "endTimestamp": "2022-01-08T16:18:52.494Z"
      },
```
Let me know if you need more info.  Thanks for your support.

**Comment by andrewkww** [comment]
Not the "semantic" files. It should be the `Records.json`. Looks like Google changed the file name.

**Comment by mimijojo** [comment]
This is what I get with the Records.json file :

> ./extract 'Records.json'
> Traceback (most recent call last):
>   File "./extract", line 82, in <module>
>     timestampms = int(o['timestampMs'])
> KeyError: 'timestampMs'

And nothing with this '2022_JANUARY.json' file

> ./extract '2022_JANUARY.json'

Maybe due to my regional settings different from yours (decimal separator, date format,...) ?

**Comment by andrewkww** [comment]
Ah, looks like Google changed the file format a little too. `Records.json` is the correct file to use. Let me update the code to handle the new format.

**Comment by andrewkww** [comment]
I just made an update to the script. It should work with the new format now. Can you update and try again?

**Comment by mimijojo** [comment]
Yes, I confirm, now it works !
Great job !

PS : I still don't understand why Google Takeout removed their KML download option.  I also don't understand why I can't find many issues raised on this removal on the internet.  You and I seem the only ones needing these gpx files.  I used those gpx for geopostioning photos and other sport tracking activities.  Anyhow, great job.  I was completely stuck.

**Comment by andrewkww** [comment]
Nice! Yeah, no idea. Maybe they found the KML format too limiting, and wanted more control over what they're outputting.
Thanks for letting me know about the issue!

**Comment by mimijojo** [comment]
Please keep maintaining this in case Google changes again their format.

Where did you get your gpx skills from ?  What's your background ?

**Comment by andrewkww** [comment]
I also use the location data for geotagging photos, so I was also relying on the KML file format.
I happen to be a software developer. These files are pretty easy to work with, so I decided to solve the issue myself. :)

**Comment by mimijojo** [comment]
:-)
