### ISSUE TITLE
Usage question regarding extracting all months

### ISSUE THREAD

**Issue by schreibman** [andrewkww/google-location-history-to-gpx#3]
First - WOW - thanks for maintaing this, as mention in other issue you are like the only one doing this.   Awesome!
Two Question -

**1.   when extracting all months:**
./extract 'Takeout/Location History/Location History.json'
./extract 'Takeout/Location History/Records.json'

The first command fails, as Takeout names semantic history YYYY/YYYY_MONTH.json
{Not that I even know what the difference between the Records and Semantic  :-) },
I can run one month at a time  by:
Copying history YYYY/YYYY_MONTH.json to 'Takeout/Location History/Location History.json'
Example 
cp  Takeout/Location History/Semantic Location History/2022/2022_DECEMBER.json 
Takeout/Location History/Location History.json
Then:
./extract 'Takeout/Location History/Location History.json' 2022-12     
./extract 'Takeout/Location History/Records.json' 2022-12

Is there another way to run this for all months without manually copying each months location history file?

**2.  If I can run for multiple months, is there a way to create a single multi-month .gpx file?**

Here is the current [01/2022] takeout structure, as you can see I have a lot of months :  

├── Takeout
│   ├── Location History
│   │   ├── Records.json
│   │   ├── Semantic Location History
│   │   │   ├── 2011
│   │   │   │   ├── 2011_DECEMBER.json
│   │   │   │   └── 2011_NOVEMBER.json
│   │   │   ├── 2012
│   │   │   │   ├── 2012_APRIL.json
│   │   │   │   ├── 2012_AUGUST.json
│   │   │   │   ├── 2012_DECEMBER.json

Thanks again, this is awesome!

**Comment by andrewkww** [comment]
The first command (`./extract 'Takeout/Location History/Location History.json'`) is actually referring to an old filename (`Location History.json`) that Google Takeout was using. Google Takeout has changed the filename for the location history to `Records.json`. I kept that old example around in case someone is using an old zip file from before.

That's also unrelated to the "semantic history" files. the `Semantic Location History` is something different, and not used by the script at all. `Records.json` should contain all the location history that you have.

**Comment by schreibman** [comment]
Thanks for the confirmation. I appreciate your work in developing and
maintaining this. It's very useful
