### ISSUE TITLE
Running this script fails with KeyError: 'latitudeE7'

### ISSUE THREAD

**Issue by evilspoons** [andrewkww/google-location-history-to-gpx#4]
Hello. Checked out the repo here into Ubuntu on WSL. Installed virtualenv and its dependencies, then ran the `source venv.sh` command. After it was done I copied in my Records.json file and did `./extract Records.json`.

It runs for a while, listing off dates that make sense based on what I know, but after it gets past 2022-09 (the file starts in 2010) it pukes out

`Traceback (most recent call last):`
`  File "/home/erik/google-location-history-to-gpx/./extract", line 134, in <module>`
`    lat = o['latitudeE7'] / 10**7`
`KeyError: 'latitudeE7'`

I'm not very good with Python so I'm not sure where to start debugging this. Any ideas?

**Comment by evilspoons** [comment]
Update: I'm a bozo and did not notice the `output` directory it was creating, and there are gpx files for everything up to 2022-09. Last GPX file is 2022-08. I'll try to look into this further later today.

**Comment by evilspoons** [comment]
I was able to run the script again skipping 2022-09, and processed 2022-10 through the 2023-02, so it doesn't seem to be a change in format in September 2022. I'd just post my Records.json, but that's a tad sensitive, so I'll keep looking at the data and see if there's anything special about the records from that month.

**Comment by andrewkww** [comment]
The `Records.json` is supposed to have `latitudeE7` and `longitudeE7` keys for the GPS data. The error you are getting suggests that the key is somehow missing. Maybe Google changed the format again. If you let me know what the current key is, I can probably update the script.

**Comment by evilspoons** [comment]
So! I figured out why the script is crashing.

Five (yes, a whopping FIVE out of nearly 2 million) points of data in the export do not have 'latitudeE7' and 'longitudeE7' values in the root of the location key.

Three of these instead contain an 'inferredLocation' subkey that looks a heck of a lot like the main keys would:

`inferredLocation : [{'timestamp': '2022-09-14T16:21:05.606Z', 'latitudeE7': 123456789, 'longitudeE7': -123456789, 'accuracy': 15}]`

(Formatting has been mangled slightly due to processing the json in Python, location censored by me)

Then two entries simply have no location data at all, they look like this:
`deviceTag : -222222222`
`platformType : ANDROID`
`osLevel : 29`
`serverTimestamp : 2022-09-13T16:09:11.350Z`
`batteryCharging : True`
`formFactor : PHONE`
`timestamp : 2022-09-13T16:08:51.140Z`

I would assume the smartest solution here is to:
1.  just skip entries that don't have any latitude/longitude keys,
2. either use the inferredLocation instead on location entries that don't have a "normal" lat/long, or just drop those too.

I looked up the particular time and dates of these 'bad' entries and I think I was taking the subway when they happened, so the phone must have started trying to figure out my location but completely failed.

**Comment by akberlin** [comment]
Skipping datasets without E7 LatLng:

```
    if 'latitudeE7' not in o or 'longitudeE7' not in o:
        continue
```

Insert directly after
```
    if args.accuracy_limit and o.get("accuracy", 0) > args.accuracy_limit:
        continue
```

Worked for me...

**Comment by andrewkww** [comment]
Yup, that should fix it. Thanks for the suggestion. I just inserted the check a little earlier in the code.
